fixed daemonset

diff --git a/host-raid/manifests/raid-daemonset.yaml b/host-raid/manifests/raid-daemonset.yaml
--- a/host-raid/manifests/raid-daemonset.yaml
+++ b/host-raid/manifests/raid-daemonset.yaml
@@ -18,11 +18,13 @@ spec:
         image: yanniszark/raid-setup:0.1
         env:
           - name: NUM_DISKS
-            value: "8"
+            value: "2"
           - name: RAID_DIR
-            value: "/mnt/raid-disks"
-          - name: DISK_DIR_PREFIX
-            value: "/dev/ssd"
+            value: "/mnt/hostfs/mnt/raid-disks/disk0"
+          - name: DISK_MNT_DIR_PREFIX
+            value: "/mnt/hostfs/mnt/disks/ssd"
+          - name: DISK_DEV_PREFIX
+            value: "/dev/sd"  
         command:
           - "/bin/bash"
           - "-c"
@@ -30,19 +32,29 @@ spec:
         args:
           - |
             set -e
+            set -x 
+            
             function sleep_forever() {
                 while true; do sleep 100; done
             }
             # If the disk has already been created, sleep indefinitely
-            if [ -d "$RAID_DIR" ]; then
+            if [ -b "/dev/md0" ]; then
                 echo "raid array already created!"
                 sleep_forever
             fi
+
+            DISK_DEV_SUFFIX=(b c d e f g h i)
+            declare -a DISKS
+            for i in `seq 0 $((NUM_DISKS-1))`;
+            do
+                DISKS[$i]="${DISK_DEV_PREFIX}${DISK_DEV_SUFFIX[$i]}"
+            done
+
             # If a disk is missing sleep indefinitely
             for i in `seq 0 $((NUM_DISKS-1))`;
             do
-                if [ -b "${DISK_DIR_PREFIX}${i}" ]; then
-                    echo "${DISK_DIR_PREFIX}${i} missing!"
+                if [ ! -b "${DISKS[$i]}" ]; then
+                    echo "${DISKS[$i]} missing!"
                     sleep_forever
                 fi
             done
@@ -50,16 +62,11 @@ spec:
             # Unmount disks from host filesystem
             for i in `seq 0 $((NUM_DISKS-1))`;
             do 
-                umount "${DISK_DIR_PREFIX}${i}" &> /dev/null || echo "Disk ${DISK_DIR_PREFIX}${i} already unmounted."
+                umount "${DISK_MNT_DIR_PREFIX}${i}" &> /dev/null || echo "Disk ${DISK_MNT_DIR_PREFIX}${i} already unmounted."
             done
             
             # Create a raid array
-            declare -a DISKS
-            for i in `seq 0 $((NUM_DISKS-1))`;
-            do
-                DISKS[$i]="${DISK_DIR_PREFIX}${i}"
-            done
-            mdadm --create /dev/md0 --level=0 --raid-devices="$NUM_DISKS" "${DISKS[@]}"
+            yes | mdadm --create /dev/md0 --force --level=0 --raid-devices="$NUM_DISKS" "${DISKS[@]}"
             
             # Format the raid array as xfs
             mkfs.xfs /dev/md0
